language:
  - python

python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - nosetests --with-coverage --cover-package eveimageserver --cover-erase --with-doctest

after_success:
  - coveralls