language:
  - python

python:
  - '2.7'
  - '3.3'
  - '3.4'

install:
  - pip install -r requirements-dev.txt

script:
  - nosetests --with-coverage --cover-package eveimageserver --cover-erase --with-doctest

after_success:
  - coveralls

deploy:
  provider: pypi
  user: regner
  distributions: "sdist bdist_wheel"
  password:
    secure: KaFDgd2lIfvLebqCxwu9DXnoPyLJA1VjjiIES4sBjUrgJkknBrOpBTbUIYTIrlc77hpxMaz+7A1tn9TghpV+9N/b4JmJBYAHyUzDQzccd5dtCZLX+9IClN68KupbF6uIWKCg7OfAZqgQf31v/x5ILjvDKNbTpGX7KzhmQCbhwRnPsmu+o8/s2QfurcWYdZmR/k7wHYFzWXg54peIxVZy7p8nvXYHVv/EWP+HTlVJE6nxby3ltlQYRFmfjJ0mqeAiVKImkICUL8CPZhiPFSO/1bAHu5KVWodzzf1ue8UQ+7vZfTNOgQmv/XWOYoPIOr8a0QSiaVtQPOoGJUJeyRY/3A6iGa+2BV8dj30mu7PBr0ftj6p3saqi7y8Q4KT3K9XYODvadDrXrl99nDXXbrS6XG2Jdh/gmAy7P2KxDWhm8hC2J/VTq/lZojQrSJ9Y6bLwyXZTvKCokbMBmETus4AX0UuqQXRFoqFvWsu7+K5LtaDTNOzuc6g9XjGlTWEd7LC+yALN80HcqjVzsRc1Be7Etlc5S1uvVJw27f+1j4rTAkissqj+98iWQVTqYLsE4zHG0ufbGDQ+ABY0oC87ZzVw18H9l8yCZmTwm1vb+4jsJzEKZ9QSHd9Q3BYYy+hnOxVmWd6aLrSvYCmfSRIBD379mitjrr9GZIkyfPNhZg+eDDA=
  on:
    tags: true
    repo: Regner/eveimageserver
